projects:
  hiv:
    data:
    - ymp_metadata.csv

pipelines:
  myqc:
    stages:
    - qc_fastqc
  process_data:
    stages:
    - trim_trimmomatic


resource_limits:
  mem:
    default: 20G
    max: 100G
  walltime:
    default: 23:59:59
  partition:
    default: short

cluster:
  profile: slurm
