---
title: "Functional Analysis"
author: "John Sterrett"
date: "2023-01-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse,
               data.table,
               ggplot2,
               phyloseq,
               patchwork,
               microshades,
               cowplot)

```

# Load data
```{r}
metadata <- fread("../metadata.txt") %>% as.data.frame()
rownames(metadata) <- metadata$PID

source("HUMAnN_to_phyloseq_helper.R")
gn <- fread("../hiv.t32.concat.humann.long/all_genefamilies_grouped_named.tsv")
rownames(gn) <- gn$`# Gene Family`
gn$`# Gene Family` <- NULL
# sanitize the sample IDs
colnames(gn) <- sapply(colnames(gn), 
                        FUN=function(x) str_split(x, "\\.")[[1]][1])

genefams <- filter_only_genes(gn)

unmapped <- genefams[1,]
rownames(unmapped) <- rownames(genefams)[1]
colSums(unmapped)/colSums(genefams)* 100

unmapped.or.ungrouped <- genefams[1:2,]
rownames(unmapped.or.ungrouped) <- rownames(genefams)[1:2]
colSums(unmapped.or.ungrouped)/colSums(genefams)* 100

genefams <- genefams %>% filter(rownames(genefams) %in% c("UNMAPPED", "UNGROUPED")==F)
# lots of unmapped and ungrouped, see here https://groups.google.com/g/humann-users/c/4Pz8NritMzw

genes <- rownames(genefams)
hier.tab <- make_pseq_tax_table_from_genefams(genes)

ecs.pseq <- phyloseq(otu_table=otu_table(genefams, taxa_are_rows=T), 
                     tax_table=tax_table(hier.tab),
                     sample_data=sample_data(metadata))

genefams.withtax <- filter_only_genes(gn, with_taxa=T)
```

# Barplot of Functional profiles {.tabset}
## Top group: L1 {.tabset}
### Subgroup: L2
```{r, warning=F, fig.height=9, fig.width=8}
make_simple_microshades <- function(pseq, group_level, subgroup_level){
    # get list of top ta1 to plot
    l1.tax <- tax_glom(pseq, taxrank=group_level) %>% tax_table()
    l1.otu <- tax_glom(pseq, taxrank=group_level) %>% otu_table()
    top.ta1 <- l1.tax[order(rowSums(l1.otu), decreasing=T),] %>% 
        as.data.frame()
    top.ta1 <- top.ta1[1:5,group_level]
    
    # prep the microshades colors
    mdf_prep <- prep_mdf(ecs.pseq, subgroup_level=subgroup_level)
    
    # create the colors object
    color_objs_GP <- create_color_dfs(mdf_prep, selected_groups=top.ta1,
                                      group_level=group_level, subgroup_level=subgroup_level,
                                      cvd = TRUE)
    # Extract
    mdf_GP <- color_objs_GP$mdf
    cdf_GP <- color_objs_GP$cdf
    # create a custom legend
    GP_legend <-custom_legend(mdf_GP, cdf_GP, 
                              legend_key_size=unit(0.4, "cm"),
                              legend_text_size=10,
                              group_level=group_level,
                              subgroup_level=subgroup_level)
    
    # plot
    plot <- plot_microshades(mdf_GP, cdf_GP)
    plot_1 <- plot + scale_y_continuous(labels = scales::percent, expand = expansion(0)) +
      theme(legend.position = "none")  +
      theme(axis.text.x = element_text(size= 7)) +
      facet_grid(~(factor(Risk_Status, levels=c("Low", "High", "Positive"))), 
               scales = "free_x", space="free_x"
             )
    
    multi <- plot_grid(plot_1, GP_legend,  rel_widths = c(1, .4))
    multi
}

make_simple_microshades(ecs.pseq, "ta1", "ta2") 
ggsave("../figures/L1_L2_microshades_METACYC.pdf", height=10, width=10)
```

### Subgroup: L3

```{r, warning=F, fig.height=9, fig.width=8}
make_simple_microshades(ecs.pseq, "ta1", "ta3")

```


### Subgroup: L4
```{r, warning=F, fig.height=9, fig.width=8}
make_simple_microshades(ecs.pseq, "ta1", "ta4")

```


## Top group: L2 {.tabset}

### Subgroup: L3
```{r, warning=F, fig.height=9, fig.width=8}
make_simple_microshades(ecs.pseq, "ta2", "ta3")

```

### Subgroup: L4
```{r, warning=F, fig.height=9, fig.width=8}
make_simple_microshades(ecs.pseq, "ta2", "ta4")

```


# Genes in Prevotella
```{r, warning=F, fig.height=9, fig.width=8}
prev.genes <- rownames(genefams.withtax) %>% grepl(pattern="Prevotella")
prev.genes.df <- genefams.withtax[prev.genes,]
rownames(prev.genes.df) <- rownames(genefams.withtax)[prev.genes]

prev.genes.df.sorted <- prev.genes.df[order(rowSums(prev.genes.df), decreasing=T),]
rownames(prev.genes.df.sorted) <- rownames(prev.genes.df)[order(rowSums(prev.genes.df), decreasing=T)]

cbind(rownames(prev.genes.df.sorted)[1:20],
      rowSums(prev.genes.df.sorted[1:20])/sum(prev.genes.df.sorted)*100) %>%
    knitr::kable(col.names=c("gene", "percent of total prevotella reads"))

prev.pseq <- phyloseq(otu_table=otu_table(prev.genes.df, taxa_are_rows=T),
                      tax_table=tax_table(ecs.pseq),
                      sample_data(metadata))

make_simple_microshades(prev.pseq, "ta1", "ta2")

```