---
title: "Nonpareil curves"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!require("Nonpareil")){
  install.packages('Nonpareil');  
}
if (!require("data.table")){
  install.packages('data.table');  
}
if (!require("ggplot2")){
  install.packages('ggplot2');  
}

setwd("/scratch/Users/jost9358/HIV-MetaG")
```

# Curves
```{r}
metadata <- data.table::fread("metadata.txt")
filepaths <- paste0("hiv.t32.concat.n40.nonpareil/", metadata$PID, ".npo")

np <- Nonpareil.set(filepaths, labels=metadata$PID)

# Show current coverage (as %)
coverages <- summary(np)[,"C"]*100 
summary(coverages)

plot(coverages, summary(np)[,"LR"]/1e9)

ggplot(mapping=aes(y=coverages,
                   x=summary(np)[,"LR"]/1e9)) +
  geom_point(size=3) +
  labs(y="Estimated Percent Coverage",
       x="Effective Sequencing Effort (Gbp)")

ggplot(mapping=aes(y=coverages,
                   x=summary(np)[,"diversity"])) +
  geom_point(size=3) +
  labs(y="Estimated Percent Coverage",
       x="Sequence Diversity Index")

hist(coverages)
hist(summary(np)[,"diversity"])
hist(summary(np)[,"LR"]/1e9)

```